#.travis.yml

language: node_js
node_js:
  - "8.12"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - master

cache:
  directories:
     - ./node_modules
     
install:
  - npm install
  
script:
  - ng build
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
